CI: improve the mathcomp-for-prosa Docker image
- Include `git` in the Docker image. It's needed by the POET CI setup.
- Set the default shell and CMD.
- Set a proper ENTRYPOINT as in the official MathComp and Rocq impages.

diff --git a/scripts/Docker/Dockerfile b/scripts/Docker/Dockerfile
--- a/scripts/Docker/Dockerfile
+++ b/scripts/Docker/Dockerfile
@@ -1,8 +1,10 @@
 FROM archlinux:base-devel
 
+SHELL ["/bin/bash", "--login", "-o", "pipefail", "-c"]
+
 RUN set -x \
     && echo "Installing packages..." \
-    && pacman -Sy --noconfirm python uv opam rsync \
+    && pacman -Sy --noconfirm python uv opam rsync git \
     && echo "Creating user..." \
     && useradd -m -u 21408 -g users rocq
 
@@ -11,9 +13,15 @@ USER rocq
 
 ADD mk-opam-switch.sh /home/rocq/
 RUN set -x \
-    && opam init --disable-sandboxing \
+    && opam init --auto-setup --yes --bare --disable-sandboxing \
     && /home/rocq/mk-opam-switch.sh \
     && eval $(opam env) \
     && opam clean -a -c -s --logs \
     && rm /home/rocq/mk-opam-switch.sh \
     && opam config list && opam list
+
+ENTRYPOINT ["opam", "exec", "--"]
+
+CMD ["/bin/bash", "--login"]
+
+LABEL maintainer="bbb@mpi-sws.org"
